insert into Airport values ('ATL', 'Hartsfield–Jackson Atlanta International Airport', 'Atlanta', 'USA');
insert into Airport values ('PEK', 'Beijing Capital International Airport', 'Beijing', 'China');
insert into Airport values ('DXB', 'Dubai International Airport', 'Dubai', 'United Arab Emirates');
insert into Airport values ('ORD', 'OHare International Airport', 'Chicago', 'USA');
insert into Airport values ('HND', 'Tokyo Haneda Airport', 'Tokyo', 'Japan');
insert into Airport values ('LHR', 'London Heathrow Airport', 'London', 'UK');
insert into Airport values ('LAX', 'Los Angeles International Airport', 'Los Angeles', 'USA');
insert into Airport values ('HKG', 'Hong Kong International Airport', 'Hong Kong', 'China');
insert into Airport values ('CDG', 'Paris-Charles de Gaulle Airport', 'Paris', 'France');
insert into Airport values ('IST', 'Istanbul Atatürk Airport', 'Istanbul', 'Turkey');
insert into Airport values ('FRA', 'Frankfurt Airport', 'Frankfurt', 'Germany');
insert into Airport values ('PVG', 'Shanghai Pudong International Airport', 'Shanghai', 'China');
insert into Airport values ('AMS', 'Amsterdam Airport Schiphol', 'Amsterdam', 'The Netherlands');
insert into Airport values ('JFK', 'John F. Kennedy International Airport', 'New York', 'USA');
insert into Airport values ('DFW', 'Dallas/Fort Worth International Airport', 'Dallas', 'USA');
insert into Airport values ('SIN', 'Singapore Changi Airport', 'Changi', 'Singapore');
insert into Airport values ('CAN', 'Guangzhou Baiyun International Airport', 'Guangzhou', 'China');
insert into Airport values ('DEN', 'Denver International Airport', 'Denver', 'USA');
insert into Airport values ('BKK', 'Suvarnabhumi Airport', 'Bankok', 'Thailand');
insert into Airport values ('SFO', 'San Francisco International Airport', 'San Francisco', 'USA');
insert into Airport values ('ICN', 'Seoul Incheon International Airport', 'Incheon', 'Republic of Korea');
insert into Airport values ('KUL', 'Kuala Lumpur International Airport', 'Kuala Lumpur', 'Malaysia');
insert into Airport values ('MAD', 'Madrid Barajas Airport', 'Madrid', 'Spain');
insert into Airport values ('DEL', 'Indira Gandhi International Airport', 'Delhi', 'India');
insert into Airport values ('LAS', 'McCarran International Airport', 'Las Vegas', 'USA');
insert into Airport values ('CLT', 'Charlotte Douglas International Airport', 'Charlotte', 'USA');
insert into Airport values ('MIA', 'Miami International Airport', 'Miami', 'USA');
insert into Airport values ('PHX', 'Phoenix Sky Harbor International Airport', 'Phoenix', 'USA');
insert into Airport values ('IAH', 'George Bush Intercontinental Airport', 'Houston', 'USA');
insert into Airport values ('SEA', 'Seattle-Tacoma International Airport', 'Seattle', 'USA');
insert into Airport values ('CTU', 'Chengdu Shuangliu International Airport', 'Chengdu', 'USA');
insert into Airport values ('YYZ', 'Toronto Pearson International Airport', 'Toronto', 'Canada');
insert into Airport values ('MUC', 'Munich Airport', 'Munich', 'Germany');
insert into Airport values ('BOM', 'Chhatrapati Shivaji International Airport', 'Mumbai', 'India');
insert into Airport values ('FCO', 'Leonardo da Vinci–Fiumicino Airport', 'Rome', 'Italy');
insert into Airport values ('LGW', 'London Gatwick Airport', 'London', 'UK');
insert into Airport values ('SYD', 'Sydney Kingsford-Smith Airport', 'Sydney', 'Australia');
insert into Airport values ('SZX', 'Shenzhen Baoan International Airport', 'Shenzhen', 'China');
insert into Airport values ('BCN', 'Barcelona–El Prat Airport', 'Barcelona', 'Spain');
insert into Airport values ('GRU', 'São Paulo-Guarulhos International Airport', 'São Paulo', 'Brasil');
insert into Airport values ('SHA', 'Shanghai Hongqiao International Airport', 'Shanghai', 'China');
insert into Airport values ('MCO', 'Orlando International Airport', 'Orlando', 'USA');
insert into Airport values ('MEX', 'Benito Juárez International Airport', 'Mexico City', 'Mexico');
insert into Airport values ('KMG', 'Kunming Changshui International Airport', 'Kunming', 'China');
insert into Airport values ('EWR', 'Newark Liberty International Airport', 'Newark', 'USA');
insert into Airport values ('NRT', 'Narita International Airport', 'Tokyo', 'Japan');
insert into Airport values ('MNL', 'Ninoy Aquino International Airport', 'Manila', 'Philippines');
insert into Airport values ('DME', 'Domodedovo International Airport', 'Moscow', 'Russia');
insert into Airport values ('TPE', 'Taiwan Taoyuan International Airport', 'Taipei', 'Taiwan');
insert into Airport values ('TSN', 'Tianjin Binhai International Airport', 'Tianjin', 'China');
